allowBuilds:
  esbuild: false
  sharp: false
minimumReleaseAgeExclude:
  - devalue@5.8.1
overrides:
  fast-xml-builder@<=1.1.6: '>=1.1.7'
  fast-xml-parser@<5.7.0: '>=5.7.0'
  postcss@<8.5.10: '>=8.5.10'
